### ISSUE TITLE
enhancement: Make sure correct version is published

### ISSUE THREAD

**Issue by kommendorkapten** [theupdateframework/tuf-on-ci#126]
This has only been seen once.

What happened?
1. During online signing, the (possibly updated) branch is [pushed](https://github.com/theupdateframework/tuf-on-ci/blob/main/actions/online-sign/action.yml#L55) to `publish`
2. Once pushed, the [publish.yml](https://github.com/theupdateframework/tuf-on-ci/blob/main/actions/online-sign/action.yml#L65) workflow is dispatched (using `ref: publish`)
3. The [upload-action](https://github.com/theupdateframework/tuf-on-ci/blob/main/actions/upload-repository/action.yml#L21) workflow then checks out the ref (i.e `publish`) and builds the TUF repository to be published.

What's occurred once is that due to a delay in GitHub, the publish job checked out the previous revision! This lead to an same version being published, i.e not the updated one.

While this seems to be an unlikely event, we should protect against it.

Proposed solution:
When the online signing action pushes `HEAD` to `publish`, it should record the git commit, and provide that as an input to the `publish` workflow, which can then be used during checkout as an input parameter (i.e specify which commit to clone). If the commit is not visible due to a delay, the workflow would fail, which is visible and can be monitored, and so, an action can be taken.

Another option is to add some logic to verify we are publishing the expected commit, and if the local commit is not the expected, the job could retry a few times with some back-off time in between. 

For simplicity, and the fact that this seem to be a rare error state, I opt for just extracting the git commit and try to checkout that specific commit.

**Comment by jku** [comment]
> When the online signing action pushes HEAD to publish, it should record the git commit, and provide that as an input to the publish workflow, which can then be used during checkout as an input parameter

Sounds good to me.
