### ISSUE TITLE
support explicit GH tokens

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf-on-ci#128]
sigstore org prevents giving GITHUB_TOKEN write access in the repository settings:
* This is reasonable for most projects but not really for the TUF repositories (root-signing and root-signing-staging).
* root-signing currently handles this with a fine grained access token that is stored as a secret. This secret is then provided as an argument to the actions

I think we should support a similar approach:
* first add an optional `token` argument to the actions
* then either
  * allow users to modify the workflows to use a secret of their choosing
  * or define a specific secret name TUF_ON_CI_TOKEN. Use that in the workflows (in tuf-on-ci-template). Something  like this might work:
    ```
    with:
       token: ${{ secrets.TUF_ON_CI_TOKEN || secrets.GITHUB_TOKEN }}
 
    ```
I like the second approach in that it likely doesn't force people to modify the workflows from the tuf-on-ci-template ones...

**Comment by jku** [comment]
As a weird idea, I wonder if this works in a workflow (in a way that actions themselves would not have to support alternative tokens at all: the workflow would just use a special token as GITHUB_TOKEN while invoking the action)

```
    env:
       GITHUB_TOKEN: ${{ secrets.TUF_ON_CI_TOKEN || secrets.GITHUB_TOKEN }}
```

**Comment by jku** [comment]
> ```
>     env:
>        GITHUB_TOKEN: ${{ secrets.TUF_ON_CI_TOKEN || secrets.GITHUB_TOKEN }}
> ```

A similar setup works in current root-signing, but only because there's custom support for using this variable: it doesn't affect actions in general so does not really help here

**Comment by jku** [comment]
Current status (note to self):
* WIP branches: [tuf-on-ci](https://github.com/jku/tuf-on-ci/commits/add-token-arg), [tuf-on-ci-template](https://github.com/theupdateframework/tuf-on-ci-template/commits/add-token-arg)
* testing deployment using a custom token : https://github.com/jku/test-token-arg
* issues to still investigate:
  * dispatches seem to happen twice for some reason -- but GH is having some sort of moment, this could be a hiccup on their end (and nothing really bad has happened as result)

**Comment by jku** [comment]
> is it possible that the "prevent workflows from automatically triggering workflows" doesn't apply to non-GITHUB_TOKEN tokens?


yes, this is explicitly how it works: _events triggered by the GITHUB_TOKEN ... will not create a new workflow run_. 

So the `createWorkflowDispatch()` tasks in both create-signing-events and online-sign need to be prevented when token is a custom token... This means I may have to redesign this completely as the actions don't currently know what kind of token they have

**Comment by jku** [comment]
> Could invent something that prevents a new comment from being made for a commit that already has a signing event comment ? 

the signing event status comments _should_ be reproducible... I guess we could produce the new signing event comment content and compare it to previous comment and if they match just skip adding a new comment?

**Comment by kommendorkapten** [comment]
> is it possible that the "prevent workflows from automatically triggering workflows" doesn't apply to non-GITHUB_TOKEN tokens?

Yes, this is true. Could that be the reason for multiple dispatches?

**Comment by jku** [comment]
hmm, I probably should split tuf-on-ci-status to two commands, `status` and `targets-update`, because we need two separate results for the GH action to make decisions:
* `targets-update` return value tells if targets metadata was modified ( this is needed to dispatch another signing-event if using GITHUB_TOKEN in this new design)
* `status` return value tells if the signing event is complete (needed e.g. for PR checks which don't currently exist)
