### ISSUE TITLE
pin dependencies more strictly?

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf-on-ci#187]
tuf-on-ci is an application (or two) and should potentially pin Python dependencies more. The decisions on these two cases may be different: the repository tools breaking because of a dependency update is a more immediate threat than signer tools breaking (think of online-signing failing because an indirect dependency accidentally changing API). Pinning specific versions could make the tools more robust but also means that if a dependency makes a security release, tuf-on-ci must make a new release and users must upgrade to that release.

### repository

The repository package `tuf-on-ci` is installed by the actions from source.
* review direct dependency pins: should these be pinned to specific version?
* consider pinning indirect dependencies

### signer

The signer package `tuf-on-ci-signer` is installed by user from pypi
* review direct dependency pins: should these be pinned to specific version?
* consider pinning indirect dependencies

**Comment by jku** [comment]
For reference, sigstore-python solves this by providing two different install methods:
* the pypi package depends on lightly pinned direct dependencies
* but there is a requirements.txt that contains fully pinned direct+indirect dependencies

... but then nobody at all seems to use the requirements.txt, not even the github action

**Comment by kommendorkapten** [comment]
I would probably lean to pin dependencies to avoid potential breakages, and then rely on Dependabot to make users update when new releases are out there. Breaking the online signing would be a catastrophic event for TUF repository.

**Comment by rdimitrov** [comment]
Would there be a great amount of time difference if you delegate that for the signer side to dependabot? My assumption is dependabot PRs get merged relatively fast, so overall it's not that much of a threat but we benefit from the consistency/stability? That is of course if the signer side starts being released more often too.

**Comment by jku** [comment]
At the moment it would be fine. I'm just thinking a year or two forward, were all focusing on other projects or maybe on summer vacation... Is anyone invested enough to make those releases?

**Comment by jku** [comment]
So after a bit of thinking and discussion, my initial plan for _repository_ is to 
* pin all direct and indirect deps in a `requirements.txt`
* use requirements.txt in the actions
* update requirements.txt using dependabot (or something home-grown with pip-tools) once a week or so
* Make tuf-on-ci releases regularly or whenever dependabot mentions a security update in a dependency

**Comment by jku** [comment]
Hmm, as far as I can tell, dependabot won't actually do what we want (update the pinned list of indirect dependencies of a specific pyproject.toml, adding and removing indirect dependencies as needed). So I guess I do this manually like a caveman...

**Comment by rdimitrov** [comment]
Maybe I remember this wrongly but was it @kommendorkapten that was doing something with dependabot that allowed it to do these things? I'm sorry if I'm completely wrong but I have some memory of seeing a PR somewhere that looked useful for this 😃

**Comment by kommendorkapten** [comment]
@rdimitrov I think what you referred to is that I mentioned that you can enable auto-merge for dependabot updates when all checks are passing?

**Comment by jku** [comment]
I have a draft #248 -- I'm not very keen on it but I guess running that _and_ dependabot kind of works:
* normal upgrades to requirements.txt can be done with dependabot
* adding/removing indirect deps happens with the workflow

**Comment by jku** [comment]
> we should be able to verify that tuf-on-ci-sigstore-test is still running on the pinned version

This is visible now: pinned dependencies are indeed installed for the actions.

**Comment by jku** [comment]
So status right now is:
* repo dependencies are 100% pinned: we will see how this works
* signer is not fully pinned

I think this is reasonable for now.
