### ISSUE TITLE
Running tool multiple times on the same signing event fails due to existing remote branch

### ISSUE THREAD

**Issue by joshuagl** [theupdateframework/tuf-on-ci#207]
`git push` fails when trying to run the tool a second time for the same signing event where the event branch has changed. The git push is rejected by remote due to the branch name already existing on my forked remote and being a non-fast-forward change.

My local git repository state is the same as immediately following the previous succesful signing event, but the remote barnch (fork) state has changes.

> Press enter to push signature(s) to origin/sign/staging-with-more-signers:
> To https://github.com/joshuagl/root-signing-staging.git
>  ! [rejected]        HEAD -> sign/staging-with-more-signers (non-fast-forward)
> error: failed to push some refs to 'https://github.com/joshuagl/root-signing-staging.git'
> hint: Updates were rejected because a pushed branch tip is behind its remote
> hint: counterpart. Check out this branch and integrate the remote changes
> hint: (e.g. 'git pull ...') before pushing again.
> hint: See the 'Note about fast-forwards' in 'git push --help' for details.
> Traceback (most recent call last):
>   File "/Users/joshuagl/Projects/github/sigstore/root-signing-staging/.venv/bin/tuf-on-ci-sign", line 8, in <module>
>     sys.exit(sign())
>              ^^^^^^
>   File "/Users/joshuagl/Projects/github/sigstore/root-signing-staging/.venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
>     return self.main(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/joshuagl/Projects/github/sigstore/root-signing-staging/.venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
>     rv = self.invoke(ctx)
>          ^^^^^^^^^^^^^^^^
>   File "/Users/joshuagl/Projects/github/sigstore/root-signing-staging/.venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/joshuagl/Projects/github/sigstore/root-signing-staging/.venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
>     return __callback(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/joshuagl/Projects/github/sigstore/root-signing-staging/.venv/lib/python3.12/site-packages/tuf_on_ci_sign/sign.py", line 75, in sign
>     git_echo(
>   File "/Users/joshuagl/Projects/github/sigstore/root-signing-staging/.venv/lib/python3.12/site-packages/tuf_on_ci_sign/_common.py", line 97, in git_echo
>     subprocess.run(cmd, check=True, text=True)
>   File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 571, in run
>     raise CalledProcessError(retcode, process.args,
> subprocess.CalledProcessError: Command '['git', 'push', '--progress', 'origin', 'HEAD:refs/heads/sign/staging-with-more-signers']' returned non-zero exit status 1.

**Comment by joshuagl** [comment]
I worked around this by syncing the branch on the fork with the branch on the main repo. Deleting the branch on the fork would presumably have worked too.

**Comment by joshuagl** [comment]
Interesting but related issue, if the remote branch exists (a new branch isn't created) `git` does not suggest creating a PR:

> Press enter to push signature(s) to origin/sign/staging-with-more-signers:
> Enumerating objects: 9, done.
> Counting objects: 100% (9/9), done.
> Delta compression using up to 8 threads
> Compressing objects: 100% (5/5), done.
> Writing objects: 100% (5/5), 583 bytes | 583.00 KiB/s, done.
> Total 5 (delta 4), reused 0 (delta 0), pack-reused 0
> remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
> To https://github.com/joshuagl/root-signing-staging.git
>    100f5f4..775b50d  HEAD -> sign/staging-with-more-signers

**Comment by jku** [comment]
Thanks. Clearly we've not tested the non-maintainer flows well enough:
* this doesn't come up for maintainers because we're pushing and pulling to same branch on same repo
* we could generate a new name for the fork branch everytime, but then github wouldn't know where to suggest the PR..
* we could just force push the branch -- sounds a little scary but should be ok

**Comment by joshuagl** [comment]
Force push might be OK, but you still run into the issue of git not suggesting you open a PR when it's pushing to an existing branch.

Maybe delete then push (even scarier?)
