### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf-on-ci#3]
I'd like to make the first release before we add any features in the new repository:
* point isn't so much stability guarantees, more the ability for TUF repositories to upgrade from version to version
* signer release (to pypi) would be nice to have but not critical
* the core thing is to tag a release in git so that the template can start pinning it (I'd suggest pinning the hash but a tag works too)

@lukpueh, @kommendorkapten do you have anything you want done before a release? My list is currently:
* cleanup the python dependencies for both signer and repo: no depending on git main: either depend on a release version from pypi or if that's not possible, pin a git hash
* maybe get the signer pypi releases going

**Comment by jku** [comment]
> signer release (to pypi) would be nice to have but not critical

I think the first pypi release has to be made with password or apitoken anyway so this can be manual -- this is because trusted publishing can only be enabled for existing projects and a project gets created by the first upload

**Comment by lukpueh** [comment]
> @lukpueh, @kommendorkapten do you have anything you want done before a release? My list is currently:
> 
> * cleanup the python dependencies for both signer and repo: no depending on git main: either depend on a release version from pypi or if that's not possible, pin a git hash
> * maybe get the signer pypi releases going

Sounds reasonable to me. I don't have anything to add.

**Comment by kommendorkapten** [comment]
I think all this sounds good. I think creating a tag for the release is valuable, but pinning the workflows to a hash is better as tags are mutable. Common is to add a comment with the tag used so it's easier to navigate when browsing workflow files to see what composite actions they are using.

**Comment by jku** [comment]
Note to myself on  the dependencies:

>  "sigstore @ git+https://github.com/sigstore/sigstore-python@7d4af6c5f6732ef12e5bb455962321ebe5cce137",

this is needed -- this is currently one of the few commits that works for us (as the last release has a buggy API). To use a release sigstore we need a new release, and then we need to update securesystemslib SigstoreSigner to use that API.

>  "securesystemslib[gcpkms,hsm,sigstore] @ git+https://github.com/secure-systems-lab/securesystemslib",

AzureSigner is not currently released:
* should pin a git hash
* should make a securesystemslib release and then pin that

>  "tuf @ git+https://github.com/theupdateframework/python-tuf",

I think we can use 3.0.0, no need to use git here.

>  "click",

we should pin a release

**Comment by jku** [comment]
python deps are now handled but since we provide GH actions for others to use, we must handle those dependencies as well: #8 creates the dependabot config that will trigger an avalanche of minor actions updates

**Comment by jku** [comment]
v0.0.1 now exists on GH. I'll close this and open a new issue with the previous comment details
