### ISSUE TITLE
repository description json links are incorrect

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf-on-ci#353]
Example https://tuf-repo-cdn.sigstage.dev/index.html

the links point to e.g. https://tuf-repo-cdn.sigstage.dev/root-signing-staging/8.root.json when it should be https://tuf-repo-cdn.sigstage.dev/8.root.json

**Comment by jku** [comment]
This looks like a weird feature of the markdown publishing.

the markdown we generate is as expected:

    root ([json](8.root.json))

but the html generated by `actions/jekyll-build-pages` then contains 
    root (<a href="/root-signing-staging/8.root.json">json</a>)`

So it does some pages specific link rewriting even if there is no need for it here :(

**Comment by jku** [comment]
Yes a jekyll feature: https://github.com/jekyll/jekyll/issues/7621: relative links are not a thing.

potential fixes:
* remove the broken json links 
* try to add the links using actual embedded html links -- it's unlikely but maybe jekyll does not rewrite those?
* rewrite the feature so it outputs HTML in the first place and not markdown

**Comment by jku** [comment]
There's something here that I donät understand still: the simplest possible reproducer with the same exact markdown has relative links! https://jku.github.io/test-pages/

**Comment by joshuagl** [comment]
I think this is related to gh-pages addons to jekyll? https://jekyllrb.com/docs/github-pages/#project-page-url-structure

**Comment by jku** [comment]
Probably yes: that's likely how the extra directory ends up in there... but I think it's not useful to resolve this issue since jekylls "relative url" is not actually relative but an absolute url path.

The trick of using html tags works for the json links so I think I'll close this as good enough...

**Comment by joshuagl** [comment]
SGTM :+1:
