### ISSUE TITLE
Bump version and resign delegation on signer change

### ISSUE THREAD

**Issue by kommendorkapten** [theupdateframework/tuf-on-ci#411]
Observed behaviour:

When a delegation's key is changed, but not the delegated target, the delegation's role metadata file is is not resigned. (Only the delegator requires resigning).

Expected behaviour:

Both the delegator and the delegation's metadata is resigned. As the delegation's role metadata is signed with the previous key, it won't be verified properly as that key is not a valid signer in the updated delegator's version.

**Comment by jku** [comment]
let's see what happens in the actual signing events -- I think this might actually mostly work in the actual signing-event pr.

**Comment by kommendorkapten** [comment]
Duplicate of #95
