### ISSUE TITLE
automate storing signing key configuration

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf-on-ci#49]
Currently supported offline keys (yubikeys, sigstore) don't strictly speaking require any configuration (they just require the user to make sure the correct signing method, like Yubikey is available). This is possible because sigstore keys can be recognised and everything else is assumed to be HSM - so th code is able to guess a Signer type 

The code allows configuring them in the signer config file though:
```
[signing-keys]
762cb22caca65de5e9b7b6baecb84ca989d337280ce6914b6440aea95769ad93 = hsm:2?label=YubiKey+PIV+%2315835999
01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546b = file:path/to/mykey?encrypted=false
```

It would be perfectly possible to automatically write uris at least for hsm signers (Yubikeys) when the public key from the yubikey is added to metadata.
* I'm a bit hesitant to modify a user written config file automatically 
* these could go into a separate application data file as well? there's likely no reason to keep this config project specific?

**Comment by jku** [comment]
> I'm a bit hesitant to modify a user written config file automatically

Thinking this through, maybe it is not configuration: it's just a cache?
* during delegation (or accepting an invite) when user is choosing which key to use, we could offer all keys from the cache as possible options (along with "new sigstore identity" and "new yubikey")
* When key is added to a role, the keyid-signeruri combo is stored in the cache
* when user needs to sign with a key, the keyid is used to lookup the correct signeruri

I don't think this cache needs to be repository specific: it can be just an application cache like `~/.cache/tuf-on-ci-sign/signing-keys.json`

**Comment by lukpueh** [comment]
I think this makes sense. The authoritative part is when key is added to a role. I can't see another step in the process, where the user would configure the uri explicitly.

**Comment by jku** [comment]
I will create a new issue with the "key cache" idea and close this
