### ISSUE TITLE
feature: support external delegated targets

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf-on-ci#75]
From sigstore-rootsigning meeting: The registry.npmjs.org role is 
1. managed externally, outside of the repository 
2. actually signed by a KMS key

We should make sure we either support this setup or figure out how to fulfill the  requirements otherwise:
* I think  _targets role signed by online keys_ in general is a good feature
* some internal or external process creating a signing event branch with a fully signed delegated targets change should "just work" already (the idea here is that the merging requires maintainer approval even if the key is online, because the online process is external... but I can see an argument for just merging automatically)
* creating the delegation needs some thinking -- 
  * probably we could just add KMS choice to the `tuf-on-ci-delegate` UX, but then the KMS would need to add the signature to the signing event branch? Or we need to allow creating a delegation without the roles metadata
  * alternatively adding the delegation is also expected to happen externally (and just magically appears in a signing event branch): we just make sure online keys are allowed in the repository code.
 * this would need to be documented well -- that the actual maintenance of the delegated role is not currently handled by tuf-on-ci

**Comment by jku** [comment]
After some thinking:
* normal signing events should indeed "just work" if the external signer is just another signer from the repositorys perspective
* when an update to the delegated target is needed:
  * external automation (or a human) creates the new metadata version , commits it, and pushes the commits to a signing event branch on the repository
  * signing event automation sees the branch, creates an issue and updates the event status: it should now be fully signed and ready to merge
* delegation changes are trickier but they can be considered a UX problem: 
  * we need to allow "importing" KMS keys as (offline) signers
  * but unlike online KMS keys we probably don't want to embed the  the private key uri (`x-tuf-on-ci-online-uri`) in the key but instead want to use `x-tuf-on-ci-keyowner` -- for the repository this is not a online key but just a signer that uses signing events like all the other signers?

**Comment by kommendorkapten** [comment]
> but unlike online KMS keys we probably don't want to embed the the private key uri (x-tuf-on-ci-online-uri) in the key but instead want to use x-tuf-on-ci-keyowner -- for the repository this is not a online key but just a signer that uses signing events like all the other signers?

Yes, that makes a lot of sense.

Worth considering is that in Sigstore root-signing, we don't blindly accept a new delegation with an external key, as part of adding the delegate's metadata and the public key (for inclusion into `targets.json`), we also require a POP (Proof of possession, which in this case is a signature over the delegate's name and the merge base commit for the branch that adds the metadata back). This is then verified before the delegate can be added. I think that could be a useful flow here too, to make sure a human error does not introduce the wrong key for the delegate.

**Comment by jku** [comment]
> Worth considering is that in Sigstore root-signing, we don't blindly accept a new delegation with an external key, as part of adding the delegate's metadata and the public key (for inclusion into targets.json) we also require a POP (Proof of possession, which in this case is a signature over the delegate's name and the merge base commit for the branch that adds the metadata back). 

Now that you said it, I realize the same may be true here, at least for the initial delegation:  the signing event for the delegation change probably does not consider the signing event ready until the _delegated metadata_ is correctly signed -- meaning the external signer has to push a signed delegated metadata version to this signing event branch.

**Comment by kommendorkapten** [comment]
Yes, when adding a new delegation, if the initial change does contains the signed metadata, no POP would be needed 👍

**Comment by jku** [comment]
Thinking the delegation change case (like creating a new delegated external role) through again, this might work:
* repository maintainer runs `tuf-on-ci-delegate` to delegate to new role "external" -- this needs some changes in our code
* signing event is incomplete because the new role is not signed
* external signing machinery is somehow triggered (to work on this signing event branch, not main), this does KMS signing (or whatever, that's the external signers business)
* signed metadata is pushed to signing event branch in repository
* signing event is complete

It's close to the normal case (where external signing machinery decides to do a new metadata version):
* external signing machinery is triggered and (starting with main branch) creates a new version of "external" role metadata
* signed metadata change is pushed to a new signing event branch in repository
* signing event is complete

I'm sure there's other ways to do this but that seems like an option: Required changes in tuf-on-ci seems minimal, I'm not sure how much work it is build the external signing system

**Comment by jku** [comment]
> repository maintainer runs tuf-on-ci-delegate to delegate to new role "external" -- this needs some changes in our code as discussed above

I said changes are needed ... but I'm going through this process in my head and maybe nothing is needed in tuf-on-ci:
* From tuf-on-ci perspective this signer is just another human signer
* Currently we require a signer name that looks like a github username:  this could be changed but something like `@-delegated-signer` works fine if the user does not actually exist (the `@-` prefix is not valid for GH usernames)
* the external signing automation obviously does require workflow(s) and code to do it. I don't object to including it in tuf-on-ci if it fits there and we can test it... but it could live outside as well. 

The external signer needs to handle two events. Both have a couple of options (**bold** for items handled by external system):
   1. Initial delegation
       * This can be initiated by tuf-on-ci-delegate in upstream repo:
           * upstream maintainer adds delegation, invites the external signer in a signing event
           * **external signer adds public key to the delegation in targets.json and removes the entry from .signing-event-state file**
           * **external signer signs the delegated metadata**
           * **external changes are  pushed to signing event branch** 
           * upstream signers sign the delegation changes
       * Or it can be handled by external system completely :
           * **external signer creates new delegation, creates new delegated metadata. adds public key to the delegation in and removes the entry from .signing-event-state file**
           * **external signer signs the delegated metadata**
           * **external changes are  pushed to signing event branch** 
           * upstream signers sign the delegation changes
   2.  signing artifact changes
       * this can be initiated by upstream repo maintainers:
           * make the artifact change in a signing event branch in upstream repo: metadata changes happen automatically
           * **trigger external signer to sign, push the commit to signing event**
       * or it could be done completely externally:
          * **trigger external system that makes artifact change, metadata change and signing**
          * **push signing event branch that contains all of those changes**

**Comment by kommendorkapten** [comment]
One approach I have been thinking about would:

We have two repositories, the `tuf-repository`, and the `delegate-repository`. The delegate-repository is not strictly needed, but for the scenarios I care about (npm) it's a must. The primary function of the `delegate-repository` is a way to manage automation, and federation with the Cloud KMS. From tuf-on-ci's perspective it does not matter, but running tuf-on-ci-sign via automation does require some modifications.

The step I envisions are listed below. For this to work, the `delegate-repository` would be configured in such a way that it has push access to the `tuf-repository`, but this is a detail that's irrelevant here. Another scenario could be that it just stores the signed file in the `delegate-repository`, which is then manually pushed to the `tuf-repository`.

### Crete the delegation

This step happens manually, inside a shell:

```shell
~/git/tuf-repo-test-4 % tuf-on-ci-delegate sign/delegate-test-1 new-delegate
Remote branch not found: branching off from main
Signing event sign/delegate-test-1 (commit 30d7a0e)
Creating a new delegation for new-delegate

Configuring role new-delegate
 1. Configure signers: [@kommendorkapten], requiring 1 signatures
 2. Configure expiry: Role expires in 365 days, re-signing starts 60 days before expiry
Please choose an option or press enter to continue: 1
Configure signers.
 1. Configure offline signer [@kommendorkapten]
 2. Configure online signer []
Please choose an option or press enter to continue: 1
 1. Sigstore
 2. Google Cloud KMS
 3. Azure Key Vault
 4. AWS KMS
<same options as when configuring online signer for timestamp/snapshot>
 1. Configure signers: [azurekms://vault.vault.azure.net/<key>/<version>], requiring 1 signatures
 2. Configure expiry: Role expires in 365 days, re-signing starts 60 days before expiry
Please choose an option or press enter to continue:
<delegate is signed>
Press enter to push changes to origin/sign/delegate-test-1:
```

### Sign the delegation

The steps listed in this example are intended to be run with automation, so I added a flag `--no-prompt` that forces tuf-on-ci-sign to not require user input. I also took inspiration from `tuf-on-ci-delegate` to allow the role to be added after the event name. By doing so, we can resolve which key to use, and if the key have `x-tuf-on-ci-online-uri`, no further prompt is made, it's assume the environment is configured with sufficient access to the vault.

```
~/git/tuf-repo-test-4 % tuf-on-ci-sign --no-prompt sign/update-delegate-test-1 new-delegate
Signing event sign/update-delegate-test-1 (commit 35bc62d)

Signing using key: azurekms://vault.vault.azure.net/<key>/<ersion>
Your signature is requested for role(s) {'new-delegate'}.

new-delegate v2
 * Expiry period: 365 days, signing period: 60 days
   (expiry period was None days, signing period was None days
 * New artifact 'new-delegate/file1.txt'
<signing happens>
Enumerating objects: 9, done.
Counting objects: 100% (9/9), done.
Delta compression using up to 10 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 1.35 KiB | 1.35 MiB/s, done.
Total 5 (delta 3), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
To github.com:kommendorkapten/tuf-repo-test-4.git
   35bc62d..c2c353b  HEAD -> sign/delegate-test-1
```

**Comment by kommendorkapten** [comment]
Current ux:

```
(.venv) kommendorkapten@m1m14:~/git/tuf-repo-test-4 % tuf-on-ci-delegate sign/ext-del-update
Remote branch not found: branching off from main
Signing event sign/ext-del-update (commit 5f71ec1)
Enter name of role to modify: new-delegate
Modifying delegation for new-delegate

Configuring role new-delegate
 1. Configure signers: [@-test-1], requiring 1 signatures
 2. Configure expiry: Role expires in 365 days, re-signing starts 60 days before expiry
Please choose an option or press enter to continue: 1
Choose what keytype to use:
1. Configure offline signers:
2. Configure online signers
Please choose an option or press enter to continue: 2
 1. Sigstore
 2. Google Cloud KMS
 3. Azure Key Vault
 4. AWS KMS
Please select online key type [1]: 3
Enter Azure vault name []: fsn-vault-2
Enter key name []: ec-key-1
 1. Configure signers: [azurekms://fsn-vault-2.vault.azure.net/keys/ec-key-1/46ddcdd5e5484810940096cb3298e87a], requiring 1 signatures
 2. Configure expiry: Role expires in 365 days, re-signing starts 60 days before expiry
Please choose an option or press enter to continue:
Your signature is required for role(s) {'new-delegate'}.

new-delegate v2
Press enter to push changes to origin/sign/ext-del-update:
Enumerating objects: 13, done.
Counting objects: 100% (13/13), done.
Delta compression using up to 10 threads
Compressing objects: 100% (9/9), done.
Writing objects: 100% (9/9), 1.62 KiB | 1.62 MiB/s, done.
Total 9 (delta 7), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (7/7), completed with 4 local objects.
remote:
remote: Create a pull request for 'sign/ext-del-update' on GitHub by visiting:
remote:      https://github.com/kommendorkapten/tuf-repo-test-4/pull/new/sign/ext-del-update
remote:
To github.com:kommendorkapten/tuf-repo-test-4.git
 * [new branch]      HEAD -> sign/ext-del-update
```

Then to sign (online):

```
(.venv) kommendorkapten@m1m14:~/git/tuf-repo-test-4 % tuf-on-ci-online-sign --role new-delegate --push
Online sign (new-delegate)
[sign/ext-del-update 8e762f5] Online sign (new-delegate)
 1 file changed, 1 insertion(+), 1 deletion(-)
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 10 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 731 bytes | 731.00 KiB/s, done.
Total 4 (delta 3), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
To github.com:kommendorkapten/tuf-repo-test-4.git
   c1ecdff..8e762f5  HEAD -> sign/ext-del-update
```

Then sign targets:
```
(.venv) kommendorkapten@m1m14:~/git/tuf-repo-test-4 % tuf-on-ci-sign  sign/ext-del-update
Signing event sign/ext-del-update (commit 8e762f5)
Your signature is requested for role(s) {'targets'}.

targets v9
 * Modified delegation new-delegate
   * Signers: 1/1 of ['azurekms']
     (was: 1/1 of ['@-test-1']
Enter pin to sign:
Press enter to push changes to origin/sign/ext-del-update:
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 10 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 711 bytes | 711.00 KiB/s, done.
Total 4 (delta 3), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
To github.com:kommendorkapten/tuf-repo-test-4.git
   8e762f5..ce94796  HEAD -> sign/ext-del-update
```

**Comment by jku** [comment]
I can try leaving some detailed comments on the PR (and I will try this as well) but  as overall comments:
* The idea of keeping the functionality in the "repository side" seems good
* I think the PR is not complete enough to close this issue as it does not include the GH action changes
* Combining current online-sign functionality and this new (I'll call it online-sign-targets just to have name) may not be correct after all: 
   * current online-sign is a bit special since it handles timestamp and snapshot: combining very different targets signing  into it seems like it was not useful
   * thinking about the missing action changes, I think we'll want a completely new action as well that calls the new online-sign-targets code... this seems inline with the previous point: we should have a separate action and a separate `tuf-on-ci online-sign-targets` command
* What I'm not sure about is whether we can somehow automate figuring out which roles get signed and when: this seems like a big open design question that gets anwsered when the action exists:
    * does user configure a workflow where the new action gets a "rolename" input argument? This does not feel like amazing UX but should work... in future we could add something to the key metadata so this would not be needed
    * if this is running within the upstream repository then triggering it seems fairly clear: the new action call could be just added to signing-event workflow (this should be tested though)
    * if this is runnning in external fork, its' a bit unclear to me: maybe fork maintainer forks the signing event branch too, a workflow is dispatched (manually or based on `sign/*` branch push), the workflow runs online-sign-targets, fork maintainer makes a PR to upstream signing event?      

* On the configuration UX side 
  * the decision to make the online signatures completely separate from offline ones is not 100% obvious to me (like why is threshold always 1 if an online sig is used? why can't I have both offline and online sigs?): timestamp and signature are implementation details of tuf-on-ci and that's why they are always threshold 1 but I don't see why same would hold for targets signatures... 
  * I think it's not obvious what "online" and "offline" mean when the user is asked to choose between them... I think listing all keytypes (offline and online) in a single list would be more understandable -- but that of course won't work if online sigs are a special case with special threshold setting

**Comment by jku** [comment]
I see that you're on vacation -- if I have time this week I will try some of the ideas above

**Comment by jku** [comment]
I keep trying some variations of GH actions to handle this... and so far it looks to me like this actually belongs in `signing-event`:
* online targets signing is supposed to happen during a signing event
* signing-event even already modifies targets metadata
* I think this should work for both external (fork) and internal workflows

The only open issue I can see is that signing-event needs to somehow figure out which roles it should sign:
* since I think we want to support external and internal forks this needs to be a per repo setting -- embedding this info in metadata seems fishy
* just trying to sign everything that is a kms key also feels wrong
* easiest option would be an action input: list of role names to sign. Another might be some repository variable but those are hidden  and only easily visible to maintainers

I think I'll give the action input argument a try and see what it looks like.

**Comment by kommendorkapten** [comment]
Let's discuss this more in person, but there is a scenario to consider, where the repository that is managing the delegation is not a fork of the upstream TUF repo. Such scenarios are more likely to be custom in their actions, and how to detect a modified delegated target. For that I would envision that the delegation maintainer signs the targets metadata and "manually" opens a PR against the upstream TUF repository. As forks can not be private (visibility can not be changed), I would think this will happen in at least one scenario (Sigstore TUF root).
