### ISSUE TITLE
Use PRs in signing events instead of issues

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf-on-ci#78]
I originally chose to use issues for signing events because creating incomplete PRs felt wrong -- a pull request implies its ready to be merged. However:
* as @kommendorkapten pointed out it's harder to explain to people who are familiar with GitHub projects
* In any case we need tests that prevent merging if the PR is incomplete so there's no safety issue really
* connection between PR and branch is stronger (and easier to review)
* I don't think there's technically anything that prevents just using PRs instead of issues as signing events

The only thing that's somewhat confusing is that you end up with signature PRs to a branch that is itself a (signing event) PR branch already...

**Comment by jonnystoten** [comment]
I think this is a good idea. I agree that it's a bit confusing to have an issue that tracks a branch rather than a PR, and anecdotally this is something that a lot of people have commented on when I show them my testing repo built with tuf-on-ci.

I've also got myself in a muddle when I've manually created a PR rather than using the link on issue that adds 'Closes #X' to the PR description. Once that PR is merged, the issue remains which has confused me.

I think opening a PR as draft and then marking it as ready for review when all signatures have been added would get around the problem of a PR looking like it's ready to be merged.

**Comment by jku** [comment]
I've definitely been persuaded by now: Using PRs make more sense.

I wonder if the only things needing changes are
* signing-event action
* docs

That's what it looks like after a quick glance... But I have a suspicion there might be something I'm still missing.

**Comment by jku** [comment]
I'm looking at this.

One wrinkle here is that modifying the "draft" state is not possible through the rest API. I really don't want to add yet another language to this pile of languages but it looks like well have to add a few GraphQL queries and mutations in there :(

**Comment by jku** [comment]
Also this requires a new config change:
_Allow GitHub Actions to create and approve pull requests_

**Comment by jku** [comment]
Looks pretty good: https://github.com/jku/tuf-on-ci-sigstore-test/pull/31

**Comment by kommendorkapten** [comment]
All runners have the `gh cli` installed, which can be used to create and modify PRs, e.g. mark a PR as ready: https://cli.github.com/manual/gh_pr_ready

Could this be an option, and remove some API calls?

**Comment by jku** [comment]
Technically yes but I'd *really* rather use an API than a use CLI tools as if they were API. tuf-on-ci is enough of a hack already without `system()` calls sprinkled in there (or more bash steps for things like that)...

Now that said, using graphql inside github-script feels extremely clunky. So maybe?

**Comment by kommendorkapten** [comment]
Maybe it can be separated, so each invocation to the cli would be a specific step `run: gh cli xyz` where the previous step writes output that's consumed by the succeeding step, so we don't end up with a bunch of `system()` calls. Maybe the interaction is more complex, but just a though.

Something like
```yaml
    - name: Mark PR ready for review
      # dispatch if using default token: otherwise update_targets step has already triggered a push event
      if: steps.verify_signatures.outputs.threshold_reached == 'true'
      shell: bash
      run: |
         gh pr ready ${{ steps.verify_signatures.outputs.pr_number }}
```

**Comment by jku** [comment]
Yes we have three options to modify the PR:
1. use javascript to interact with two different GH APIs (with graphql being pretty clunky)
1. use javascript to interact with GitHub rest API and gh CLI via `command("gh pr ...")`
1. start using bash  to interact with `gh`

Generally speaking I had been hoping to minimize shell use but none of these are particularly appealing choices.

**Comment by kommendorkapten** [comment]
> Generally speaking I had been hoping to minimize shell use (and lot of github conditional coplexity) but none of these are particularly appealing choices.

Agree, but if `gh cli` is limited to step execution for I/O with GitHub and then use python in between, maybe it wont be so bad as it would be a separation of concerns (assuming it would be fairly easy to structure the code in such a way)
